steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/waterfight:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/waterfight:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
        'run', 'deploy', '--image', 'gcr.io/$PROJECT_ID/waterfight:$COMMIT_SHA', '--region', 'us-central1',
        '--project=$PROJECT_ID', '--region=us-central1',
        '--set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID',
        '--set-env-vars=LOG_LEVEL=${_LOG_LEVEL}',
        '--platform=managed', '--max-instances=1', '--allow-unauthenticated', 'waterfight-staging-01']
    env:
      - '_LOG_LEVEL=${_LOG_LEVEL}'        
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
        'run', 'deploy', '--image', 'gcr.io/$PROJECT_ID/waterfight:$COMMIT_SHA', '--region', 'us-central1',
        '--project=$PROJECT_ID', '--region=us-central1',
        '--set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID',
        '--set-env-vars=LOG_LEVEL=${_LOG_LEVEL}',
        '--platform=managed', '--max-instances=1', '--allow-unauthenticated', 'waterfight-staging-02']
    env:
      - '_LOG_LEVEL=${_LOG_LEVEL}'        
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
        'run', 'deploy', '--image', 'gcr.io/$PROJECT_ID/waterfight:$COMMIT_SHA', '--region', 'us-central1',
        '--project=$PROJECT_ID', '--region=us-central1',
        '--set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID',
        '--set-env-vars=LOG_LEVEL=${_LOG_LEVEL}',
        '--platform=managed', '--max-instances=1', '--allow-unauthenticated', 'waterfight-staging-03']
    env:
      - '_LOG_LEVEL=${_LOG_LEVEL}'        
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
        'run', 'deploy', '--image', 'gcr.io/$PROJECT_ID/waterfight:$COMMIT_SHA', '--region', 'us-central1',
        '--project=$PROJECT_ID', '--region=us-central1',
        '--set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID',
        '--set-env-vars=LOG_LEVEL=${_LOG_LEVEL}',
        '--set-env-vars=PLAYER_MODE=guard',
        '--set-env-vars=WHITELISTED_URLS=https://staging-01.waterfight.imrenagi.com,https://production-qualification.waterfight.imrenagi.com,https://production-final.waterfight.imrenagi.com',
        '--platform=managed', '--max-instances=1', '--allow-unauthenticated', 'waterfight-staging-04']
    env:
      - '_LOG_LEVEL=${_LOG_LEVEL}'
images:
  - gcr.io/$PROJECT_ID/waterfight:$COMMIT_SHA
