version: '3.9'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.27
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
    expose:
      - "16686"
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    restart: always
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    expose:
      - "4317"
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    volumes:
      - "${PWD}/hack/observability:/observability"
    command: ["--config=/observability/otel-config.yaml", "${OTELCOL_ARGS}"]
    restart: always
    environment: {}
    depends_on:
      - jaeger

volumes: {}
