apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: waterfight
build:
  artifacts:
    - image: gcr.io/workstation-test-365315/waterfight-skaffold # must match in artifactOverrides
      context: .
profiles:
  - name: helm
    build:
      artifacts:
        - image: gcr.io/workstation-test-365315/waterfight-skaffold # must match in artifactOverrides
          context: .
      local: {}
    deploy:
      helm:
        releases:
          - name: waterfight-skaffold-k8s
            chartPath: deployment/helm/app
            artifactOverrides:
              image: gcr.io/workstation-test-365315/waterfight-skaffold
            imageStrategy:
              helm: { }
            wait: true
            recreatePods: true
            namespace: default
  - name: k8s
    build:
      artifacts:
        - image: gcr.io/workstation-test-365315/waterfight-skaffold
      local:
        useDockerCLI: false
        useBuildkit: false
    deploy:
      kubectl:
        manifests:
        - "deployment/k8s/*.yaml"
