apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: waterfight
build:
  artifacts:
    - image: gcr.io/io-extended-2023-demo/waterfight-skaffold
      context: .
profiles:
  - name: helm
    build:
      artifacts:
        - image: gcr.io/io-extended-2023-demo/waterfight-skaffold
          context: .
      googleCloudBuild: {}
    deploy:
      helm:
        releases:
          - name: waterfight-skaffold-k8s
            chartPath: deployment/helm/app
            namespace: default
            recreatePods: true
            skipTests: true
            setValueTemplates:
              global.image.name: "{{.IMAGE_REPO_gcr_io_io_extended_2023_demo_waterfight_skaffold}}"
              global.image.tag: "{{.IMAGE_TAG_gcr_io_io_extended_2023_demo_waterfight_skaffold}}@{{.IMAGE_DIGEST_gcr_io_io_extended_2023_demo_waterfight_skaffold}}"
