apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: waterfight-dev-bot-01
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containerConcurrency: 1
      timeoutSeconds: 300
      containers:
        - image: gcr.io/io-extended-2023-demo/waterfight-skaffold
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: GOOGLE_CLOUD_PROJECT
              value: io-extended-2023-demo
            - name: LOG_LEVEL
              value: DISABLED
            - name: PLAYER_MODE
              value: normal
#            - name: TRACING_MODE
#              value: google_cloud_trace
          resources:
            limits:
              cpu: 1000m
              memory: 256Mi
  traffic:
    - percent: 100
      latestRevision: true
