all:
  hosts:
    staging-waterfight:
      ansible_host: 34.136.247.132
      log_level: DEBUG
      git_branch: develop
      web_url: "staging.waterfight.imrenagi.com"
    # prod-qualification:
    #   ansible_host: 34.67.95.6  
    #   web_url: "production-qualification.waterfight.imrenagi.com"
    # prod-final:
    #   ansible_host: 34.67.95.6
    #   web_url: "production-final.waterfight.imrenagi.com"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_port: 22
    ansible_user: imre.nagi
    ansible_ssh_private_key_file: ~/.ssh/google_compute_engine
    google_cloud_project: cloudrun-hackathon-359002
    git_branch: main
    log_level: DISABLED    
    envoy_apt_release_channel: main
    envoy_apt_arch: amd64
