all:
  hosts:
    waterfight:
      ansible_host: 34.136.247.132
      log_level: INFO
      git_branch: cd
      web_url: "staging.waterfight.imrenagi.com"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_port: 22
    ansible_user: imre.nagi
    ansible_ssh_private_key_file: ~/.ssh/google_compute_engine

    google_cloud_project: cloudrun-hackathon-359002
    git_branch: main
    log_level: INFO    
    envoy_apt_release_channel: main
    envoy_apt_arch: amd64
